{{- if .Values.discordBot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pedro-discord.fullname" . }}-discord
  labels:
    {{- include "pedro-discord.labels" . | nindent 4 }}
    app.kubernetes.io/component: discord
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pedro-discord.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: discord
  template:
    metadata:
      labels:
        {{- include "pedro-discord.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: discord
    spec:
      containers:
        - name: discord-bot
          image: "{{ .Values.discordBot.image.repository }}:{{ .Values.discordBot.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 6060
              protocol: TCP
          env:
            {{- range .Values.discordBot.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "pedro-discord.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}