{{- if .Values.discordBot.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pedro-discord
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pedro-bots.labels" . | nindent 4 }}
    app.kubernetes.io/component: discord
{{- end }}