name: docker build twitch

on:
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
            platforms: linux/amd64, linux/arm64
            context: .
            file: cli/twitch/twitchBot.Dockerfile
            push: ${{ github.event_name != 'pull_request' }} ## only push on the merge event
            tags: ${{ github.event.release.tag_name }}
      - name: COPY CONTAINER IMAGE NAME
        run: echo "CONTAINER IMAGE:" ${{ github.ref_name }}-${{ github.event.release.tag_name }}
