name: docker build discord

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  discord-docker-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: cli/discord/discordBot.Dockerfile
          push: ${{ github.event_name != 'pull_request' }} ## only push on the merge event
