name: Go
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-discord:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23

    - name: Build Discord
      run: go build -v -o pedro ./cli/discord
  build-twitch:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24

    - name: Build build twitch
      run: go build -v -o pedro ./cli/twitch

  lint:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4 
      with:
        only-new-issues: true
        skip-cache: true

  test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24
    - name: Go Test
      run: go test ./... -v -cover -covermode=atomic
