name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run integration tests nightly at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pedro_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Install dependencies
      run: go mod download

    - name: Setup test database
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/pedro_test?sslmode=disable
      run: |
        go run database/migrations/*.sql || echo "Migration setup not yet implemented"

    - name: Run Integration Tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/pedro_test?sslmode=disable
        LLAMA_CPP_PATH: "mock://test"
        DISCORD_SECRET: ${{ secrets.DISCORD_TEST_TOKEN }}
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_TEST_CLIENT_ID }}
        TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_TEST_CLIENT_SECRET }}
      run: |
        cd tests
        go test -v -timeout 30s ./...

    - name: Run Load Tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/pedro_test?sslmode=disable
        LLAMA_CPP_PATH: "mock://test"
      run: |
        cd tests
        timeout 60s go run . || echo "Load test completed"

    - name: Run Benchmarks
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/pedro_test?sslmode=disable
        LLAMA_CPP_PATH: "mock://test"
      run: |
        cd tests
        go test -bench=. -benchmem -run=^$ ./...

  load-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || contains(github.event.head_commit.message, '[load-test]')
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pedro_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Extended Load Test
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/pedro_test?sslmode=disable
        LLAMA_CPP_PATH: "mock://test"
      run: |
        cd tests
        timeout 300s go run . || echo "Extended load test completed"
        
    - name: Archive Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: load-test-results
        path: tests/*.log